### ISSUE TITLE
Running *.bat file opens console with incorrect encoding

### ISSUE THREAD

**Issue by unv-unv** [consulo/consulo-batch#2]
When I run *.bat file from windows command line, it uses CP866 code page and correctly displays cyrillic symbols:
![изображение](https://user-images.githubusercontent.com/16825982/144659365-f94e4bb3-33ff-4351-ac72-6d27ac38df0f.png)

But when I'm running this file from Consulo it opens console with incorrect encoding and cyrillic symbols are displayed incorrectly:
![изображение](https://user-images.githubusercontent.com/16825982/144659495-0fccae8a-8c48-4446-bfd9-27cde8bc8b73.png)

Also this console doesn't display character colors.

**Comment by unv-unv** [comment]
And how do I select encoding for the script?

**Comment by VISTALL** [comment]
![9b1a378865c591e9897287c588b4](https://user-images.githubusercontent.com/542934/144679217-b20925cf-df41-4a99-a462-d6e3a11bf6de.png)

bottom left. IBM866

**Comment by unv-unv** [comment]
OK. But why it's IBM866 while it's usual name is CP866?

**Comment by VISTALL** [comment]
@unv-unv it's alias of cp866 in java ;) and cp866 is same as ibm866 :)

**Comment by unv-unv** [comment]
I understand that it's only my fault that I don't know correct internal name for encoding. It's merely user fault if he/she knows international name of encoding but not the internal name which library creators selected for it ;)

**Comment by unv-unv** [comment]
One more issue. Script runner by default uses as working directory not the directory script located in but JRE directory. And if I manually split script name and working directory runner is no more able to select encoding for console by using script encoding:
![изображение](https://user-images.githubusercontent.com/16825982/144680554-8770c4ba-f155-47d5-a142-9011f26d84a2.png)

**Comment by VISTALL** [comment]
Hmm. I created it with empty work dir, and it set to correct dir not jre
![ce79f37aeb0ccff20cb973379636](https://user-images.githubusercontent.com/542934/144681058-5b0fb572-f9b1-4986-9d3a-09d07e949375.png)

**Comment by VISTALL** [comment]
> I understand that it's only my fault that I don't know correct internal name for encoding. It's merely user fault if he/she knows international name of encoding but not the internal name which library creators selected for it ;)

It's not internal name :)

https://en.wikipedia.org/wiki/Code_page_866

> MIME / IANA | IBM866

cp866/766 only alias :)

**Comment by unv-unv** [comment]
![изображение](https://user-images.githubusercontent.com/16825982/144681365-7bd5df4c-50ce-4419-89fd-0b45e80d73f3.png)

**Comment by VISTALL** [comment]
xD my bad

**Comment by VISTALL** [comment]
pushed fix
